const data = {
  blended_spices: [
    {
      id: 1,
      images: "./public/Blended_Spices_(16)/BIRYANI_MASALA.png",
      name: "Biriyani Masala",
      price: "",
      description: "",
    },
    {
      id: 2,
      images: "./public/Blended_Spices_(16)/CHAT_MASALA.png",
      name: "Chat Masala",
      price: "",
      description: "",
    },
    {
      id: 3,
      images: "./public/Blended_Spices_(16)/CHHOLE_MASLA.png",
      name: "Chhole Masala",
      price: "",
      description: "",
    },
    {
      id: 4,
      images: "./public/Blended_Spices_(16)/CHICKEN_MASALA.png",
      name: "Chikan Masala",
      price: "",
      description: "",
    },
    {
      id: 5,
      images: "./public/Blended_Spices_(16)/EGG_CURRY_MASALA.png",
      name: "Egg Curry Masala",
      price: "",
      description: "",
    },
    {
      id: 6,
      images: "./public/Blended_Spices_(16)/FISH_MASALA.png",
      name: "Fish Masala",
      price: "",
      description: "",
    },
    {
      id: 7,
      images: "./public/Blended_Spices_(16)/GARAM_MASALA.png",
      name: "Garam Masala",
      price: "",
      description: "",
    },
    {
      id: 8,
      images: "./public/Blended_Spices_(16)/MUTTON_MASALA.png",
      name: "Mutton Masala",
      price: "",
      description: "",
    },
    {
      id: 9,
      images: "./public/Blended_Spices_(16)/PAV_BHAJI_MASALA.png",
      name: "Pav Bhaji Masala",
      price: "",
      description: "",
    },
    {
      id: 10,
      images: "./public/Blended_Spices_(16)/PULAV_BIRYANI_MASALA.png",
      name: "Pulav Biryani Masala",
      price: "",
      description: "",
    },
    {
      id: 11,
      images: "./public/Blended_Spices_(16)/SAMBHAR_MASALA.png",
      name: "Sambhar Masala",
      price: "",
      description: "",
    },
    {
      id: 12,
      images: "./public/Blended_Spices_(16)/SHAHI_PANEER_MASALA.png",
      name: "Sahi Paneer Masala",
      price: "",
      description: "",
    },
    {
      id: 13,
      images: "./public/Blended_Spices_(16)/TANDOORI_CHICKEN_MASALA.png",
      name: "Tandouri Chicken Masala",
      price: "",
      description: "",
    },
  ],
  bean_oli_seads: [
    {
      id: 1,
      image: "./public/Beans_&_Oil_Seeds_(05)/SESAME_SEEDS_BLACK.png",
      name: "SESAME SEEDS BLACK",
      price: 230.0,
      description: "",
      moisture: "8% Max.",
      purity_natural_white: "99%, 99 / 1 / 1 & 99.5%",
      oil_content: "48% Min",
      color_of_natural_black: "Blackish",
      packing: "Bulk 25/50 kgs PP bags.",
    },
    {
      id: 2,
      image: "./public/Beans_&_Oil_Seeds_(05)/SESAME_SEEDS_NATURAL_WHITE.png",
      name: "SESAME SEEDS NATURAL WHITE",
      price: 230.0,
      description: "",
      moisture: "8% Max.",
      purity_natural_white: "99%, 99 / 1 / 1 & 99.5%",
      oil_content: "48% Min",
      color_of_natural_black: "Creamish",
      packing: "Bulk 25/50 kgs PP bags.",
    },
    {
      id: 3,
      image: "./public/Beans_&_Oil_Seeds_(05)/SESAME_SEEDS_HULLED.png",
      name: "SESAME SEEDS HULLED",
      price: 230.0,
      description: "",
      moisture: "8% Max.",
      purity_natural_white: "99.90%, 99.95%, 99.97, 99.98, 99.99%",
      oil_content: "48% Min",
      color_of_natural_black: "Whitish",
      packing: "Bulk 25/50 kgs PP bags.",
    },
  ],

  dehydrated_vegetables: [
    {
      id: 1,
      images: "./public/Dehydrated_Vegetables_(07)/white_onion_flakes.png",
      name: "white onion flakes",
      price: "",
      description: "",
      quality: "Flakes, Kibbled, Minced",
      color: "Creamy Whitish",
      size: "5 to 18 mm",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "<60 PPM",
      packing: "Nett 14 / 20 KG PP Bag Inside and Paper Bag Outer Side",
    },
    {
      id: 2,
      images: "./public/Dehydrated_Vegetables_(07)/white_onion_powder.png",
      name: "white onion powder",
      price: "",
      description: "",
      quality: "",
      color: "Creamy Whitish",
      size: "Up to 100 MESH",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "<60 PPM",
      packing: "Nett 14 / 20 KG PP Bag Inside and Paper Bag Outer Side",
    },
    {
      id: 3,
      images: "./public/Dehydrated_Vegetables_(07)/red_onion_flakes.png",
      name: "red onion flakes",
      price: "",
      description: "",
      quality: "Flakes, Kibbled, Minced",
      color: "Creamy Reddish / Pinkish",
      size: "5 to 18 mm",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "<60 PPM",
      packing: "Nett 14 / 20 KG PP Bag Inside and Paper Bag Outer Side",
    },
    {
      id: 4,
      images: "./public/Dehydrated_Vegetables_(07)/red_onion_powder.png",
      name: "red onion powder",
      price: "",
      description: "",
      quality: "",
      color: "Creamy Reddish / Pinkish",
      size: "Up to 100 MESH",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "<60 PPM",
      packing: "Nett 14 / 20 KG PP Bag Inside and Paper Bag Outer Side",
    },
    {
      id: 5,
      images: "./public/Dehydrated_Vegetables_(07)/",
      name: "garlic flakes / cloves",
      price: "",
      description: "",
      quality: "",
      color: "Dark Creamish",
      size: "8 to 15 mm",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "<60 PPM",
      packing: "Nett 14 / 20 KG PP Bag Inside and Paper Bag Outer Side",
    },
    {
      id: 6,
      images: "./public/Dehydrated_Vegetables_(07)/garlic_granules.png",
      name: "garlic granules",
      price: "",
      description: "",
      quality: "",
      color: "Cream White",
      size: "0.5 mm to 1 mm / 1 mm to 3 mm / 3 mm to 5 mm",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "10 PPM Max.",
      packing: "Nett 14 / 20 / 25 KG PP Bag Inside and Paper Bag Outer Side",
    },
    {
      id: 7,
      images: "./public/Dehydrated_Vegetables_(07)/garlic_powder.png",
      name: "garlic powder",
      price: "",
      description: "",
      quality: "",
      color: "Cream White",
      size: "Up to 100 MESH",
      moisture: "6%",
      total_ash: "5% Max.",
      acid_insoluble_ash: "0.5% Max.",
      hot_water_insoluble: "20%",
      sulphur_dioxide_so2: "10 PPM Max.",
      packing: "Nett 14 / 20 KG PP Bag Inside and Paper Bag Outer Side",
    },
  ],
  dry_fruits: [
    {
      id: 1,
      image: "./public/Dry_Fruits_(02)/CASHEW_NUTS.png",
      name: "CASHEW NUTS",
      price: "",
      description: "",
      color: "Black, Golden Yellow, Brown",
      type: "W 180, W 240, W 320, W 450, Split, LHW, Broken",
      moisture: "6%",
      broken: "5% Max.",
      packing: "Nett 10 kg / 25 IB",
    },
    {
      id: 2,
      image: "./public/Dry_Fruits_(02)/RAISINS.png",
      name: "RAISINS",
      price: "",
      description: "",
      color: "Black, Golden Yellow, Brown",
      type: "Black Raisins, Golden Raisins, Malayar Raisins",
      moisture: "13% to 15%",
      packing:
        "Nett 14 / 20 KG PP Transparent Bag Inside and Carton Box Outer side",
    },
  ],
  eduble_oils: [],
  flours: [],
  fryums_and_wafers: [],
  ground_powder_spices: [
    {
      id: 1,
      image: "./public/Ground_Powder_Spices_(09)/CUMIN_SEEDS.png",
      name: "CUMIN SEEDS",
      price: "",
      description: "",
      quality: "Singapore / Europe",
      purity: "98%, 99%, 99.5% Min.",
      admixture: "2%, 1%, 0.5% Max.",
      moisture: "09% Max.",
      volatile_oil: "Min 1.5 ml / 100 gm",
      acid_insoluble_ash: "1.75% Max.",
      total_ash: "8% Max.",
      packing: "Bulk 25/50 kgs PP bags.",
    },
    {
      id: 2,
      image: "./public/Whole_Spices_(10)/CORIANDER_SEEDS.png",
      name: "Coriander Seeds",
      price: "",
      description: "",
      quality: " Eagle, Scooter, l Parrot, ll Parrot",
      purity: "99%, 99.50% Min.",
      admixture: "1%, 0.50% Max.",
      moisture: "10% Max",
      ash: "8% Max.",
      acid_insoluble_ash: "1.5% Max.",
      packing: "Bulk, Totes, 25/50 kg PP bags.",
    },
    {
      id: 3,
      image: "./public/Whole_Spices_(10)/FANNEL_SEEDS.png",
      name: "Fennel Seeds",
      price: "",
      description: "",
      quality: "Singapore / Europe",
      purity: "99%, 99.5% Min.",
      admixture: "1%, 0.5% Max.",
      moisture: "9% Max.",
      volatile_oil: "2ml / 100 gm Min.",
      acid_insoluble_ash: "1.25% Max.",
      packing: "25/50 kg PP bags.",
    },
    {
      id: 4,
      image: "./public/Whole_Spices_(10)/CHILI_WHOLE.png",
      name: "Fenugreek Seeds",
      price: "",
      description: "",
      quality: "Singapore / Europe",
      purity: "99%, 99.50% Min.",
      admixture: "1%, 0.50% Max.",
      moisture: "10% Max",
      acid_insoluble_ash: "1.25% Max.",
      packing: "25/50 kg PP bags.",
    },
  ],
  indian_groceries: [],
  khakhara: [],
  indian_branded_food: [],
  ready_to_eat_products: [],
  uncategorized: [],
  whole_spices: [
    {
      id: 1,
      image: "./public/Ground_Powder_Spices_(09)/TURMERIC_POWDER.png",
      name: "Turmeric Fingers / Powder",
      price: "",
      description: "",
      type: "Nizam, Erode, Salem",
      polished: "Single Polished, Double Polished",
      moisture: "10% Max",
      buld: "2%",
      curcumin: "1.8% to 5%",
      acid_insoluble_ash: "1.5% Max.",
      total_ash: "9% Max.",
      packing: "25/50 kg Jute /  PP bags.",
    },
    {
      id: 2,
      image: "./public/Ground_Powder_Spices_(09)/CHILI_POWDER.png",
      name: "Chili Whole / Powder",
      price: "",
      description: "",
      quality: "Sanam S4 / 334 / 273, Teja S17, S12 & Byadgi etc.",
      scoville_index: "12,000 SHU to 90,000 SHU",
      moisture: "11% Max. for Whole and 9% for Powder",
      aflatoxin: "Less Than 5 or Up to 15 PPB as per condition.",
      color_value: "50 to 100 ASTA",
      length: "More than 5.5 CM",
      packing: "Gross / Nett 25 / 50 KG PP Bags, Jute Bags, Paper Bag.",
    },
    {
      id: 3,
      image: "./public/Ground_Powder_Spices_(09)/CRUSHED_CHILI_FLAKES.png",
      name: "Chili Flakes / Crush",
      price: "",
      description: "",
      quality: " Sanam S4 / 334 / 273, Teja S17, S12 & Byadgi etc.",
      scoville_index: "12,000 SHU to 90,000 SHU",
      moisture: "10% Max.",
      aflatoxin: " Less Than 5 or Up to 15 PPB as per condition.",
      packing: "Gross / Nett 25 / 50 KG PP Bags, Jute Bags, Paper Bag.",
    },
  ],
};
